### ISSUE TITLE
how is this different to Una's?

### ISSUE THREAD

**Issue by sturobson** [iamarek/Sly-Gulp-Starter#1]
Hey

I'm just about to spin this up for some quick prototype testing <3 

It'd be great if there was a list in the readme explaining what's different :)

**Comment by achatys** [comment]
Hey @sturobson  it's a bit more adjusted to my own needs while I was doing this. Happy to provide some list later on. Also just to be clear I reached Una directly to ask if she's ok with making this started open source  :) Happy to hear any feedback about this

**Comment by iamarek** [comment]
Hey @sturobson it's a bit more adjusted to my own needs while I was doing this. Happy to provide some list later on. Also just to be clear I reached Una directly to ask if she's ok with making this starter open source :) Happy to hear any feedback about this

**Comment by iamarek** [comment]
- Removed deploy function
- Uglify and Concat removed from js task, moved to separate min-js task
- 'watch' task checks for changes in fonts and push them to the directory in dist
- Added partials to the boilerplate so you can create separate files for pieces of page and use them across different pages (check folder html/partials for examples)
- Added grid code to scss/grid
- Added useful mixins
- Added variables for grid
- Added function for rem sizes
- Added structure of SCSS
- Mocha tests

**Comment by sturobson** [comment]
Thanks for this -- I've not had to spin up a new project in 3 years and thought to try yours... It's working great so far -- thank you <3
